// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv1irnjbrmzsTR0gvJ5tcnWstUvbSZlNs',
    appId: '1:221388689588:web:1a90638f57bd4b82ea47e1',
    messagingSenderId: '221388689588',
    projectId: 'mobile-modul-6-6b139',
    authDomain: 'mobile-modul-6-6b139.firebaseapp.com',
    storageBucket: 'mobile-modul-6-6b139.firebasestorage.app',
    measurementId: 'G-V4SQ48CB1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWhHe6dEmQGKW4ExXYWC1vlQ4tcVwgICY',
    appId: '1:221388689588:android:2a6ab2a8d87e9e9dea47e1',
    messagingSenderId: '221388689588',
    projectId: 'mobile-modul-6-6b139',
    storageBucket: 'mobile-modul-6-6b139.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmJMYdhllkESOWKj7y_-qLbaA3s3KD--o',
    appId: '1:221388689588:ios:eb778f126967901eea47e1',
    messagingSenderId: '221388689588',
    projectId: 'mobile-modul-6-6b139',
    storageBucket: 'mobile-modul-6-6b139.firebasestorage.app',
    iosBundleId: 'com.example.demo3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmJMYdhllkESOWKj7y_-qLbaA3s3KD--o',
    appId: '1:221388689588:ios:eb778f126967901eea47e1',
    messagingSenderId: '221388689588',
    projectId: 'mobile-modul-6-6b139',
    storageBucket: 'mobile-modul-6-6b139.firebasestorage.app',
    iosBundleId: 'com.example.demo3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv1irnjbrmzsTR0gvJ5tcnWstUvbSZlNs',
    appId: '1:221388689588:web:b38fd757eca00f04ea47e1',
    messagingSenderId: '221388689588',
    projectId: 'mobile-modul-6-6b139',
    authDomain: 'mobile-modul-6-6b139.firebaseapp.com',
    storageBucket: 'mobile-modul-6-6b139.firebasestorage.app',
    measurementId: 'G-615694XZY1',
  );
}
